### ISSUE TITLE
libcudnn.cudnnCreate() cudnnStatusArchMismatch Error

### ISSUE THREAD

**Issue by Adnino** [hannes-brt/cudnn-python-wrappers#11]
Hi, I am trying to run a sample code to test my cudnn installation.
I can import libcudnn without any error. But when I run:
cudnn_context = libcudnn.cudnnCreate()
 to initialize cuDNN and return a handle to the cuDNN context

I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\libcudnn.py", line 277, in cudnnCreate
    cudnnCheckStatus(status)
  File "C:\Anaconda\lib\site-packages\libcudnn.py", line 246, in cudnnCheckStatu
s
    raise cudnnExceptions[status]
libcudnn.cudnnStatusArchMismatch

I have a nvidia geforce 635m with cuda 6.5 installed on my computer, and VS2013 professional.
is there any solution please ?

**Comment by hannes-brt** [comment]
It means your GPU is not compatible with cuDNN.
