### ISSUE TITLE
Strange output data with double

### ISSUE THREAD

**Issue by Felix-neko** [hannes-brt/cudnn-python-wrappers#7]
I've tried to use your branch for CUDNN RC2 API, but had a strange thing: when I tried to use it with `double`, the convolution gave me some strange values: about 10 ^ -312. When I switched to `float`, everithing was okay again.

Here I made a small test for this error:
https://github.com/Felix-neko/cudnn-python-bugreport

Cannot you look at it?

P.S. Thank your for your patience.
^__^

**Comment by kashif** [comment]
@Felix-neko as far as I can see... it seems to be cudnn bug... I cannot see anything wrong that we are doing in calling the APIs... I will keep looking though...

**Comment by Felix-neko** [comment]
Oy vey!

[crying]

**Comment by kashif** [comment]
another thing to check might be the `workSpaceSizeInBytes`... perhaps you can try to explicitly set it and try if that helps?

**Comment by kashif** [comment]
@Felix-neko also note that when `beta = 0` the output is not read and can contain any uninitialized data (including Nan numbers)...

**Comment by Felix-neko** [comment]
@kashif

But AFAIK, `beta=0` means that the old data, whatever it was, should be totally replaced with new data. Isn't it?

**Comment by kashif** [comment]
@Felix-neko true yes you are right... :bomb:

**Comment by kashif** [comment]
yes @Felix-neko so then can you kindly try to create a `cudnnGetConvolutionForwardAlgorithm()` with the type: `CUDNN_CONVOLUTION_FWD_NO_WORKSPACE` and use that?

**Comment by Felix-neko** [comment]
I'll try to do it when get to work. Alas, I don't have all the software installed at home.

**Comment by kashif** [comment]
@Felix-neko I just tried it... but no luck... same behaviour :-1:

**Comment by philvdm** [comment]
I think that alpha and beta are not properly handled in libcudnn_rc2.py
alpha and beta must be passed per reference but that reference MUST be of proper type (e.g double if double type is chosen). From what I see, alpha,beta are always passed as float pointers

**Comment by kashif** [comment]
@philvdm yes I thought so too, so I explicitly passed double for the double case but it did not help... the API takes just a pointer to the alphas and betas and the docs do not mention their types explicitly....

I have also emailed nvidia with this behaviour as well...

**Comment by philvdm** [comment]
I am from nvidia ;-) and I can confirm that alpha/beta needs to be of the same type than the tensor.
 
As a test, just pass Alpha=0 and beta=1, your tensor should be unchanged.

**Comment by kashif** [comment]
@philvdm ah cool thanks for the info! :cake: I will try it out...

**Comment by kashif** [comment]
@philvdm :tada: cool it works! I will fix up the bindings to set the appropriate ctype depending on the datatype of the tensor/filter...

**Comment by hannes-brt** [comment]
Thank you very much @kashif, @philvdm, and @Felix-neko for solving this. I just checked again and it works for me too now.

**Comment by Felix-neko** [comment]
Can you also update your cudnn2 branch?

**Comment by hannes-brt** [comment]
Just use the master branch now, please. All cudnn R1 is backed up on the cudnn1 branch now, so master will have the bleeding edge R2 code.

**Comment by Felix-neko** [comment]
Great! Thank you, comrade!
^__^
